### ISSUE TITLE
Supporting SASS for the latest version?

### ISSUE THREAD

**Issue by nikitasinelnikov** [ionic-team/ionicons#1038]
Hi team,

I saw that you stop SASS using since 5.0 version, but this way is helpful for my project. 
How I can properly download the latest v6 version with actual data.json and minified CSS file. I can create SASS myself from it.

Let me know if I'm doing something wrong,
Best Regards!

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. Can you please clarify the problem you are running into?

**Comment by nikitasinelnikov** [comment]
Hi @liamdebeasi,

Thanks for your answer!

We used the 2.x version of your library earlier in our WordPress plugin. When it's time to update, we understand that we cannot support a version older than 4.5.10-1 where is possible to enqueue the library through CSS and compatible CSS files to avoid conflicts. 

Just for example, we got SASS files of FontAwesome and made some customizations to make the not-conflictable CSS files inside the WordPress plugin. 

Or am I using the wrong way to connect your library and can you suggest specific ways to how it can be connected to the WordPress plugin as CSS?
Also, what is the way I can use for getting all icons list? We have a form builder where the user can assign the icon for the field. So we need a way to get the full icons list.

I got a necessary result for 4.5.10-1 but for sure we want to support your library in the future.

Let me know your thoughts and suggestions,
Best Regards!

**Comment by liamdebeasi** [comment]
Thanks for the response and apologies for the delay. Do you have an example of the conflicting CSS that you need to adjust? The current CSS should be encapsulated within the `<ion-icon>` Web Component due to its usage of the Shadow DOM.

> Or am I using the wrong way to connect your library and can you suggest specific ways to how it can be connected to the WordPress plugin as CSS?

Can you provide an example of how you are currently consuming Ionicons in your Wordpress plugin? Typically developers use the `<ion-icon>` component, but I have also seen some examples where developers copy the SVG data and reference that directly instead (such as https://github.com/jenkinsci/ionicons-api-plugin)
