### ISSUE TITLE
ionicons path configuration 4.0.0

### ISSUE THREAD

**Issue by borian** [ionic-team/ionicons#1064]
# Bug Report

**Ionic version:** 4.0.0 

**Current behavior:**
ionicons does not follow the [webpack path configuration](https://webpack.js.org/guides/public-path/) or is configurable at runtime

**Expected behavior:**

ionicons should follow the  `__webpack_public_path__` configuration or expose a path configuration at runtime.

**Steps to reproduce:**
create new App with `ionic start` 
configure webpack resource loading path in `main.ts` by adding
```
declare let __webpack_public_path__: any;
__webpack_public_path__ = 'sub/folder/';
```
All static files generated by ionic and angular can now be served from a sub folder **except ionicons**.
With the `publicPath` configuration the app path can be configured after `ng build`  and even at runtime.

This currently prevents me from using Ionic4.  
In my use-case the ionic application path is unknown to me at build time (wordpress theme).  
All assets except ionicons are configurable.

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. In the time since this issue was opened much has changed in the Ionicons architecture, and the original configuration noted here is no longer valid. I am going to close this, but please feel free to open a new issue with a reproduction if you are still running in this problem.
