### ISSUE TITLE
feat: Make icons easily themeable

### ISSUE THREAD

**Issue by strangelookingnerd** [ionic-team/ionicons#1129]
### Describe Problem

Some icons are missing the `fill="currentColor"` attributes which makes them hard to be used in themes with different color schemes.

See https://github.com/jenkinsci/custom-folder-icon-plugin/issues/93 and https://github.com/jenkinsci/ionicons-api-plugin/pull/20 for details.

### Describe Preferred Solution

Add the `fill="currentColor"` were applicable.

### Describe Alternatives

None

### Additional Information

PR incoming.

**Comment by liamdebeasi** [comment]
Thanks for the report. Do you have an example of an ionicon that cannot be easily themed? I took a look at https://github.com/jenkinsci/custom-folder-icon-plugin/issues/93, but I was unable to reproduce this issue on my end.

For example, the "walk" icon can be themed using `color` in CSS: https://codepen.io/liamdebeasi/pen/LYmaZvz However, this appears broken in https://github.com/jenkinsci/custom-folder-icon-plugin/issues/93#issuecomment-1268184670.

**Comment by strangelookingnerd** [comment]
Besides the example in my [comment](https://github.com/jenkinsci/custom-folder-icon-plugin/issues/93#issuecomment-1268184670) I do not really have a reproducer _outside_ of Jenkins context.

https://weekly.ci.jenkins.io/design-library/Symbols explains how symbols work in general for Jenkins as they are provided via https://github.com/jenkinsci/ionicons-api-plugin. Further there is more information about theming

> To make your symbol themeable, adjust the following properties:
>
>    stroke="currentColor"
>    fill="currentColor"
>
> You dont need to add both attributes, pick the one that matches your use case.

This is basically why I added them in https://github.com/jenkinsci/ionicons-api-plugin/pull/20 and thought it would be good to provide the "fix" here as well. Maybe the usage of the symbols or theming approach in Jenkins is wrong in the first place - I can't really tell. But my PR fixes the issue I had and poses no downside from what I can see.

**Comment by liamdebeasi** [comment]
Thanks for the response and apologies for the delay. Oh I see, you are using the raw SVG in the `l:icon` component instead of the `ion-icon` Web Component.

Our Web Component style applies `fill: currentColor` and `stroke: currentColor` with CSS:

Fill: https://github.com/ionic-team/ionicons/blob/0e3ba9922cf8b09396aaac17287c13cc97161ec5/src/components/icon/icon.css#L9
Stroke: https://github.com/ionic-team/ionicons/blob/0e3ba9922cf8b09396aaac17287c13cc97161ec5/src/components/icon/icon.css#L15

Would your component be able to do the same thing? My concern with making the change proposed in the PR is we would need to remember to apply these attributes to every new icon we add, otherwise theming will not work as expected. Instead, setting `fill` and `stroke` using CSS allows the theming to apply to every icon.

**Comment by strangelookingnerd** [comment]
The remarks in https://github.com/jenkinsci/design-library-plugin/issues/91 state the relevance of the fill/stroke properties being in the SVG rather than the CSS for Jenkins themes. But I'm not sure why that is. Pinging @NotMyFault and @timja for more clarification.

**Comment by timja** [comment]
cc @janfaracik too
