### ISSUE TITLE
icon request: ethernet wwan and disconnect internet

### ISSUE THREAD

**Issue by Firestar-Reimu** [ionic-team/ionicons#1145]
### Describe the Icon

1. ethernet
2. wwan(Mobile broadband modem)
3. wifi(disconnected)
4. vpn(disconnected)
5. ethernet(disconnected)
6. wwan(disconnected)

**Comment by amandaejohnston** [comment]
Thank you for the requests. I believe this issue is covered by the existing `wifi` icon, as well as these requests:
- https://github.com/ionic-team/ionicons/issues/599
- https://github.com/ionic-team/ionicons/issues/323

Could you let me know if you had anything else in mind? Example images would help.
