### ISSUE TITLE
bug: DOMParser is not defined

### ISSUE THREAD

**Issue by bonomite** [ionic-team/ionicons#1179]
### Current Behavior

getting this odd error when setting up CapacitorJS project... 

500

DOMParser is not defined

at E:\git\_NYPR\wnyc-vue-3\node_modules\ionicons\components\ion-icon.js:175:14

When manually installing 6.1.1, the issue goes away. Something went wrong with the recent 6.1.2 release.

### Expected Behavior

not have a 500 error

### Steps to Reproduce

when using the @nuxtjs/ionic module: https://ionic.nuxtjs.org/getting-started/

### Code Reproduction URL

https://stackblitz.com/edit/nuxt-starter-qbrxrh?file=nuxt.config.ts

**Comment by liamdebeasi** [comment]
Thanks for the report. Are you able to provide a sample app I can run to test this?

**Comment by bonomite** [comment]
should SSR always be off for a CapacitorJs app?

**Comment by sean-perkins** [comment]
@bonomite this problem occurs because of a recent change we made to support CSPs. The API we use to do it is the web API `DomParser`. This API is not available in a server context. However, we did not need to initialize it always and instead should have done it within an execution context that checks you are running inside of a browser. 

This will be fixed in #1180.

**Comment by bonomite** [comment]
Thanks guys!
