### ISSUE TITLE
[ERROR] install ionicons in vite

### ISSUE THREAD

**Issue by JunedSetiawan** [ionic-team/ionicons#1239]
i am trying to install ionicons in laravel vue vite (using package splade) `npm i ionicons` then i imported ionicons in resources/js/app.js
 
![image](https://github.com/ionic-team/ionicons/assets/70498944/2c1456d1-7c05-4a27-8b38-f6ddc5225c85)
 
and I get an error and warning when I look in the console 

Warning
![image](https://github.com/ionic-team/ionicons/assets/70498944/7bb658fe-be26-4d64-a05c-62bcb24555c2)

Error
![image](https://github.com/ionic-team/ionicons/assets/70498944/457638f4-4b5b-4724-af49-ed6122b596cf)

I've also tried using the unpkg script and it works without errors but I don't want the way to use unpkg.
how to fix it? I'm still a beginner

**Comment by vaynevayne** [comment]
When I used this package last year, it didn't support npm, and to this day, it doesn't seem to support it either, so you have to go with the script approach

**Comment by Gkiokan** [comment]
I got progress on that. You need to import the `ionicons.esm.js` and `ionicons.js` into your HTML Template, and then it works without the Script Tag.  But I haven't experimented with the `vite process` yet because I am usually using webpack and vite it a bit new to me.  

There is no way to implement the ionicons with require or import, both of them have different issues.  
So basically copying the dist files to your public folder and hotlinking them works.  
```
        <script type="module" src="/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="/dist/ionicons/ionicons.js"></script>
```

If there is a way to link the files with vite without running the transpiler, this should be a total win.

**Comment by liamdebeasi** [comment]
Hey there,

Apologies for the delay. Do you have a reproduction case I could look at?
