### ISSUE TITLE
bug: external link open in the same tab

### ISSUE THREAD

**Issue by BasemYahia402** [ionic-team/ionicons#1274]
### Current Behavior

external link as link GitHub repo open in the same tab 

### Expected Behavior

External link as link GitHub repo will open in the new tab

### Steps to Reproduce

Open page home on vsc
Go to links in the navbar
Add attribute target="_blank" to link

**Comment by amandaejohnston** [comment]
Thank you for the issue. It sounds like this is a bug report for Ionic Framework, instead of something specific to Ionicons. Could you open an issue there instead ([link](https://github.com/ionic-team/ionic-framework/issues/new/choose)) and ensure the template is fully filled out? Be sure to include a code reproduction.

I'm going to close this out, but if this is indeed Ionicons-specific, let me know and include a code reproduction.

**Comment by amandaejohnston** [comment]
Oh, is this about the Github link in the navbar of https://ionic.io/ionicons/? In that case, we already have an issue open for that here: https://github.com/ionic-team/ionicons/issues/953 I'll keep this closed, but this time as a duplicate. Thanks again for the report!
