### ISSUE TITLE
feat: Recommendations/Instructions for building font files

### ISSUE THREAD

**Issue by ainola** [ionic-team/ionicons#1293]
### Describe Problem

b123558 removed an older .ttf file, which makes sense. However, those that wish to use a font package (for e.g. OS status bars) are unable to do so. 

### Describe Preferred Solution

It would be nice if there were some official recommendations on how to build the icons. Even better, it'd be great if they were built for us! :P

**Comment by amandaejohnston** [comment]
The latest version of Ionicons doesn't require a separate build step, only installation. You can find instructions here: https://ionic.io/ionicons/usage

Does that help answer your question? If not, could you give more details on the specific problem you're running into?

**Comment by ainola** [comment]
Thanks for your response. Rather than using the web framework we're interested in using it as a traditional fontpack for use in a desktop environment. This uses e.g. .ttf files locally stored in the filesystem. This is so status bar programs, shell environments, word processors, and more can utilize the font.

**Comment by amandaejohnston** [comment]
We moved to SVGs instead of font files in Ionicons 4 for performance reasons -- the icon font required developers to bundle the entire set of font data (several megabytes) in their app, even if they were only using a handful of icons. You can read more about this change in the Ionicons v4 announcement here: https://ionic.io/blog/announcing-ionicons-v4

We have no plans at the moment to re-introduce the font files. If you'd still like to use them, I would recommend downgrading to an earlier version of Ionicons. (The .ttf file that was removed recently wasn't being updated, so you weren't getting the latest icons with that anyway.)

I'm going to close this, but thanks for understanding!
