### ISSUE TITLE
feat: Solution to import icons dynamically in angular

### ISSUE THREAD

**Issue by tanishqmanuja** [ionic-team/ionicons#1294]
### Describe Problem

I want to import icons dynamically at builld time

Here's a minimal example
```ts
// file: tabs.config.ts

type IonIcon = keyof typeof import("ionicons/icons");

type TabSchema = {
  path: string;
  icon: 
    | IonIcon
    | {
        default: IonIcon;
        active?: IonIcon;
      };
}

export const tabs: TabSchema [] = [
  { path: "starred", icon:  { default: "starOutline", active: "star" } }
]
```
```ts
// file tabs.page.ts

const iconmap = tabs
  .map(t => Object.values(t.icon))
  .flat(Infinity)
  .map(
    async (i): Promise<[string, string]> => [
      i as string,
      await import(`ionicons/icons`).then(m=>m[i]),
    ]
  );

const icons = Object.fromEntries(await Promise.all(iconmap));

@Component({
  selector: "app-tabs-page",
  standalone: true,
  imports: [IonTabs, IonTabBar, IonTabButton, IonIcon, IonLabel, NgFor],
  template: `...some logic...`,
})
export default class TabsPage {
  readonly tabs = tabs;
  constructor() {
    addIcons(icons);
  }
}
```

### Describe Preferred Solution

It would be easy if the new addIcons function supported adding icons only using string, like:

```
addIcons([
  "star"
])
```

**Comment by liamdebeasi** [comment]
Hey there,

Apologies for the delay. Could you clarify your use case for this?

**Comment by tanishqmanuja** [comment]
It's literally the same use case as mentioned above. What I wanted to do was put the logic of rendering tabs inside tabs.page.ts and only change a tabs.config.ts file afterwards if i ever needed. 

So idiomatically the higher abstraction thing which is the tabs.config.ts shouldn't know/care about the implementation details. Which I couldn't find the correct way to do.

Also, It may also be a more convenient syntax, if ionicons internally matched the string passed to it with the object required.

```
addIcons(["nameoftheicon"])
```

After saying that - analysis at build time of what imports are needed, honestly I don't know if there even is a way to do it in a framework agnostic manner. So you may close this for now until someone puts out a more demanding/compelling use case than mine 😅

**Comment by liamdebeasi** [comment]
> After saying that - analysis at build time of what imports are needed, honestly I don't know if there even is a way to do it in a framework agnostic manner.

My main reason for asking was this. You can currently pass the SVG data directly to the icon to accomplish this with proper build time analysis. However, this isn't a great experience in Angular since you'd need to import the SVG and then expose it as a variable on your component class.

In Ionicon 7.2 we also added the ability to autogenerate the icon name based on the SVG object. So for example if you passed `addIcons({ nameOfTheIcon })` this would create a map between `'name-of-the-icon'` and the SVG object. You'd then be able to do the following:

```html
<ion-icon name="name-of-the-icon"></ion-icon>
```

We don't offer any mechanisms for dynamically importing icons at build time since we do not interface with the compiler. but maybe something like the above would help? Alternatively, you could update your `angular.json` file to make sure that only the SVGs you want are copied over. We do [this in the Ionic Framework starter apps for Angular](https://github.com/ionic-team/starters/blob/f90735f525b618c817c98ac406cdd1e5969d7e74/angular/base/angular.json#L29-L31). You could modify that to only copy a subset of SVGs instead of all of the SVGs.

**Comment by tanishqmanuja** [comment]
I don't mind changing the angular.json. That is exactly what I did before the addIcons function was available, imported all svg(s) during the early development phase and then cherry picked only the selected svg(s) as the project settled.

But the downside was that any other team member could remove/change few icons from the template but easily forget about cleaning up angular.json. Basically managing N + 1 points of concern N being the number of icons + 1 angular.json

addIcons function definitely helped the collocation of code. But yeah i could be a singular point of concern, just like tailwind could analyse what classes are being used.

Btw don't take it as some negative criticism, that's totally not my intention. This is much better than the state of material-symbols, which you have to import a straight 3mb+ file, with no function or endpoint to 'easily' select the icons you want.

**Comment by liamdebeasi** [comment]
> But the downside was that any other team member could remove/change few icons from the template but easily forget about cleaning up angular.json. Basically managing N + 1 points of concern N being the number of icons + 1 angular.json

Yep that's a good point. It's a fairly brittle solution.

> addIcons function definitely helped the collocation of code. But yeah i could be a singular point of concern, just like tailwind could analyse what classes are being used.

I'm not sure there's a good way for us to automatically import all components you are using in your app at build time while also ensuring only the icons you are need are bundled. IonIcons does not interact wit the compiler, so our options are a bit limited here.

> Btw don't take it as some negative criticism, that's totally not my intention

None taken 😄 


-------

At the moment our best recommendation is to use `addIcons`. It doesn't do a build-time import, but it at least lets you explicitly define the icons you want to use while ensuring only those icons are added to your build. We don't currently offer any special build tooling to do an import at build time. I am going to close this, but let me know if you have any questions.

**Comment by francis-Paul-code** [comment]
Hello @liamdebeasi I see this issue was closed but it seems to be the closest to the problem I'm having. I'm fairly new to the Angular environment though have been using Ionic with react for a few years now.

**Implementation Description**
Im trying to achieve somewhat what @tanishqmanuja  was trying to achieve but in a different way and I think it should work. I've created a input component that is meant to be reusable throughout the project, It takes in an icon from the consumer and passes it into the `addIcons() `function for it to be bundled with the component.
````javascript
// input field component
@Component({
  selector: 'app-input-field',
  template: '
  <ion-icon [name]="_icon!" ></ion-icon>
',
  styleUrls: ['./input-field.component.scss'],
})
export class InputFieldComponent implements OnInit {
  @Input() hasIcon!: boolean;
  @Input() icon?: { [name: string]: string };
  private _icon!: string;

  constructor() {
    this.hasIcon && addIcons(this.icon!);
  }

  ngOnInit() {
    if (this.hasIcon) {
      this._icon = Object.keys(this.icon!)[0];
    }
  }
}
````
````javascript

//consumer component

import { add } from 'ionicons/icons';
@Component({
  selector: 'app-login',
  template: '
 <app-input-field [icon]="icon" [hasIcon]="hasIcon" ></app-input-field>
',
  styleUrls: ['./login.page.scss'],
})
export class LoginPage implements OnInit {
  hasIcon = true;
  icon = { ['add']: add };
  
  constructor() {}

  ngOnInit() {}
}
````
**Use Case**
The field is meant to be reused throught the app with different icons so the exact icon needed needs to be passed by the consumer.

**Problem**
On the component size the icon is recieved in the required format for `addIcons`, however the icon does not render, the ion-icon element renders with  an empty native. This implementation is easily  achievable in react, however in angular it seems impossible.
Any idea why this doesnt work and any suggestion for a better implementation if this one is not achievable
