### ISSUE TITLE
Two Requests: Wifi with different signal strengths & Wifi Outline

### ISSUE THREAD

**Issue by forsureitsme** [ionic-team/ionicons#323]
##### Wifi Outline

Like `ion-wifi`, but outline.
__
##### Wifi with different signal strengths

Like `ion-wifi` or `ion-android-wifi`, but with one or two bars.

Full strength signal would be the the `ion-wifi` itself.
Would be nice to have two types of low/medium strength signal:
- 1/2 bars filled and the other two just outlined. Three outlined bars would be no signal.
- 1/2 bars filled and the other two with lower opacity/hidden. Three low opacity bars would be no signal.

Not sure if I made myself clear, though...

**Comment by Ionitron** [comment]
Greetings @forsureitsme!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by forsureitsme** [comment]
No, it's not there yet.

So, ok, an example of different signal strengths would be:
![wifi-signal-strength](https://cloud.githubusercontent.com/assets/2235293/12460412/b1d2a5e4-bf9a-11e5-89f6-46169901a554.jpg)
We only have the "Excelent" as ```ion-wifi```.

---
For outlined, the same as above, but outlined.

**Comment by dcousens** [comment]
Bump,  would this be possible to add?

**Comment by bensperry** [comment]
It's certainly something we could consider adding. We're in the midsts of some other Ionic Framework development, so it probably won't get updated for some time still. Keep an eye out though!

**Comment by eXpliCo** [comment]
Will this issue get re-opened of something like that to make sure that it's not forgotten? I don't see it in the icon set yet.

**Comment by bensperry** [comment]
Now that [v4 ionicons](https://ionicons.com/) is out, we can consider adding this to the next update.

**Comment by liamdebeasi** [comment]
Thanks for the report. This was updated in https://github.com/ionic-team/ionicons/pull/1264.

**Comment by sultanmyrza** [comment]
@liamdebeasi It looks like this issue is considered closed, but I couldn’t find WiFi icons with different signal strengths at [ionic.io/ionicons](https://ionic.io/ionicons). Am I missing something?  

If Ionicons were to add WiFi icons with varying signal strengths, what would the naming convention be? Perhaps something like:  

- `network-wifi-1-bar`  
- `network-wifi-2-bar`  
- `network-wifi-3-bar`  

<img width="1485" alt="Image" src="https://github.com/user-attachments/assets/f1266ccb-de83-4681-8d8d-339314882702" />

**Would love to hear your thoughts—thanks for all your hard work on Ionicons! 🙌**

**Comment by liamdebeasi** [comment]
I don't work for Ionic anymore, but if I remember correctly the icons are still named "wifi-outline", "wifi-sharp" and "wifi". It looks like https://ionicons.com/ is using an outdated version which is why the new icons don't show up there. The icons were updated in [Ionicons 7.3](https://github.com/ionic-team/ionicons/compare/v7.2.3...v7.3.0) so make sure you are using that version.
