### ISSUE TITLE
Weird icons after rebuilt ionicons with new icons

### ISSUE THREAD

**Issue by m1kl** [ionic-team/ionicons#352]
I am on linux (Fedora 23) and I am trying to rebuild ionicons with new icons to use them on a ionic (v2) project.

I cloned the 3.0 branch, installed all the dependencies specified on the docs, I added my custom icons (svg) to the src folder and run python builder/generate.py. all seems to run without any errors, however when I try to use the new icons in my app, I get weird icons as you can see on this [link](http://postimg.org/image/k8gafhoht/).

Am I missing something?

**Comment by aeroeng** [comment]
+1
some of the svgo output icons are distorted

**Comment by aeroeng** [comment]
So, ignoring the distorted svgo output icons, my issue was that I thought it would use the app/node_modules/ionicons/dist/fonts/ionicons* but it uses the app/node_modules/ionic-framework/fonts/ionicons* so had to update those...

**Comment by aeroeng** [comment]
A tip would be to check the ionicons/cheatsheet.html after you rebuilt them and make sure your new icons are shown properly. If they are then the problem is where you put the files for your app and the class names... I had to update app/node_modules/ionicons/dist/ and app/node_modules/ionic-framework/fonts/ionicons* and restart ionic

**Comment by royipressburger** [comment]
@mickael83 where you able to fix that issue? I have them same thing and it looks like the paths are ok..
