### ISSUE TITLE
Please update the facebook icons in accordance with the official facebook brand guidelines

### ISSUE THREAD

**Issue by RashadSaleh** [ionic-team/ionicons#369]
Hello. Following this: https://www.facebookbrand.com/ , facebook describes how the "f" logo should be used, and the current facebook icons (ion-social-facebook, ion-social-facebook-outline) do _not_ follow the guidelines. Please update them with a box around the "f". Thank you.

**Comment by tech4him1** [comment]
Agree.  Can you at least add this as an option?

**Comment by rdlabo** [comment]
Set this file in your project: [logo_facebook.svg.zip](https://github.com/ionic-team/ionicons/files/4310201/logo_facebook.svg.zip)
And use for example: 

```html
<ion-icon src="path/to/logo_facebook.svg"></ion-icon>
```

Thanks.

**Comment by danieljameswilliams** [comment]
Thank you @rdlabo 
But I still think that the ionicons should see to this :)

**Comment by amandaejohnston** [comment]
Thank you for the report. Looking at their most recent guidelines [here](https://about.meta.com/brand/resources/facebookapp/) and [here](https://about.meta.com/brand/resources/facebookapp/guidelines/), I don't see any reference to a box around the logo anymore. Since our icon is currently up to date with the brand standards, I'm going to close this out, but please let me know if you have any questions or if I missed the guidelines you were referring to.
