### ISSUE TITLE
Request: No connection

### ISSUE THREAD

**Issue by FrancescoMussi** [ionic-team/ionicons#382]
There is already the wifi icon.
Could be nice to have the same icon, empty, to indicate there is no connection.

Thanks!

**Comment by Bouzmine** [comment]
+1

**Comment by amandaejohnston** [comment]
Thank you for the request. We have a couple other similar issues that may cover this:
- https://github.com/ionic-team/ionicons/issues/323
- https://github.com/ionic-team/ionicons/issues/599

Another possible option would be to use the existing `wifi` icon, but use the `color` CSS property to make it gray.

I'm going to close this out since it sounds like we already have the possible use cases covered elsewhere, but let me know if you had a different use case in mind.
