### ISSUE TITLE
Request: Please update currency icons

### ISSUE THREAD

**Issue by sandhanapandian** [ionic-team/ionicons#389]
ionicons is really good, but currency icons are not having more count,

**Comment by amandaejohnston** [comment]
Thank you for the request. If you have specific currency icons you'd like to see that we don't currently have, please open a feature request for each one so we can make sure your use cases are covered. Please search the existing issues first, though; for example, we already have a GBP icon request here: https://github.com/ionic-team/ionicons/issues/376

Due to the age of this post and lack of information, I'm going to close this out, but let me know if you have any questions.
