### ISSUE TITLE
Continue?

### ISSUE THREAD

**Issue by John-Luke** [ionic-team/ionicons#438]
This repo will be continued? Because I see many issues, PR, missing icons and the last commit has in January. I would like to know it

**Comment by royipressburger** [comment]
Joining the question.

**Comment by John-Luke** [comment]
@adamdbradley

**Comment by alzearafat** [comment]
bump bump!

**Comment by bensperry** [comment]
Hey all,

We are 100% continuing support for ionicons. We've just been really *really* busy working on the next version of the Framework. Once that is in Final, we plan to spend time updating and going through Ionicons issues as well as updating the site.

Thanks for your patience and stay tuned!

**Comment by trucle** [comment]
+1

**Comment by wbhob** [comment]
@John-Luke changes are continuing on the 3.0 branch.

**Comment by alzearafat** [comment]
Wow! Thanks! :D

**Comment by mickeyl** [comment]
Ionicons are great.  It's somewhat of a shame that they need to wait for the new framework. I'm sure many people are using them detached from the framework. FontAwesome just landed a spectacular crowd funding campaign, would that perhaps be an option for Ionicons as well?

**Comment by wbhob** [comment]
@mickeyl There are actually a lot of icons available right now. Ionic will probably not be taking the route of a Kickstarter since they are venture-backed. Since Ben is the primary designer (CDO), he has been super busy working on designing Ionic Framework 2. As he said earlier, the team will be working on Ionicons pretty soon now that 2.0.0 final is out.

**Comment by alzearafat** [comment]
I love ionicons. It's great!

I use it almost on every projects. Really wish it's continue developed @bensperry

**Comment by mickeyl** [comment]
Please update 😀

**Comment by adamdbradley** [comment]
Sorry this repo hasn't received a lot of attention, we've been focused on Ionic itself and our latest project Stencil. The great news is that ionic will be ported to become a stencil component, and all of the icons will be svgs rather than font icons. Additionally, with the font icon the user needed to download all of them, as a stencil component and refactoring, users will only have to download the exact icons which the page is using. With this new structure, it'll allow us to add even more icons without worrying about bloating filesize further, and slowing down apps. We've got a great working example already and hope to add this to Ionicons 4.0 soon. Please stay tuned! This repo hasn't been forgotten about.

**Comment by mickeyl** [comment]
Sounds good, but please add the SVGs in addition, not as a replacement for the fonts. Icon fonts are very useful in particular with native apps on mobile platforms.

**Comment by adamdbradley** [comment]
@mickeyl Yup agreed. We're not removing the icon fonts at all, and the web components are an addition like you said. More info is here: https://github.com/ionic-team/ionicons/issues/499
