### ISSUE TITLE
Ionic shows wrong icon

### ISSUE THREAD

**Issue by xBelabz** [ionic-team/ionicons#469]
I meet some strange problem using Ionicons :

1 - I installed with [component](https://github.com/component/component):
$ component install driftyco/ionicons

2 - I add an import to my app.scss : 
@import '../../components/ionicons/css/ionicons';

3 - in my HTML :
`<button ion-button block icon-right color="secondary">`
    ` <i class="icon ion-home"></i>`
         `Home`
`</button>`

The result : 
<img width="139" alt="screen shot 2017-03-04 at 20 09 02" src="https://cloud.githubusercontent.com/assets/26189634/23581566/775959da-0116-11e7-98be-a9c232d89d2e.png">

Normally we should see a house !

Any suggestion please ?
Thanks for your help.

**Comment by mhoennig** [comment]
Same problem here with Ionicons 3.0.0 / Ionic 4.3.3 / Angular 5.0.0. This code:
`<ion-icon class="back-button-icon icon icon-md back-button-icon-md ion-md-arrow-back" role="img" ng-reflect-klass="back-button-icon" ng-reflect-ng-class="back-button-icon-md" aria-label="arrow back" ng-reflect-name="md-arrow-back"></ion-icon>`
(generated by "ionic-img-viewer": "^2.9.0")
shows the ice-cream icon instead of the back button.

And that's exactly what can be found in ionicons.svg:
`<glyph glyph-name="ion-md-arrow-back" unicode="&#xf27d;" horiz-adv-x="342" `
Unicode f27d is the ice-cream icon according to [this cheatsheet](http://ionicons.com/cheatsheet.html)

My guess is some versions do not fit together, I've just not yet figured out which precisely.

**Comment by mhoennig** [comment]
As a workaround I added this to my app.scss:
```
.ion-md-arrow-back:before {
    content: "\f2ca";
}
```

**Comment by mlncn** [comment]
Hitting the same exact same issue (just tested the back button to ice cream cone) with Ionic included by Bulma  :-(

**Comment by mlncn** [comment]
OK, i had updated Bulma+Ionic with node, but the ionicon.eot, .svg, .ttf, and .woff files were still old.  Rather than updating those files, i deleted them and upgraded to doing icons the now-recommended web components way:

1. Load its JavaScript in your app or page, `https://unpkg.com/ionicons@4.5.0/dist/ionicons.js`
2. Use an ionic web component, `<ion-icon name="arrow-back"></ion-icon>`

And all is happiness.  Per [Ionicons](https://ionicons.com/) recommended [usage](https://ionicons.com/usage).  Definitely better than the old fonts+classes way.

**Comment by vaporizationator** [comment]
I temporarily solved the problem by copying the correct woff2 file into my www (or dist) folder manually.
https://ionicons.com/fonts/ionicons.woff2?v=4.5.5

I was trying to use "gift" but it was displaying "ice-cream" in ios and "happy" in android. It was using characters \199 and \191 repespectivally. A quick check on ionicons.com revealed that these characters correctly refer to "gift", and work correctly on ionicons.com. This lead me to believe there were mismatches in my fonts file, so I copied the font file directly from ionicons.com, and voila.  
I am using ionic-angular@3.9.2

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. I am going to close as there is not enough information for us to verify this bug. If this is still a problem with the latest version of Ionicons, please reply to this thread with a GitHub repo that we can use to verify the reported behavior.
