### ISSUE TITLE
ion-tabs: Variable tabIcon

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionicons#494]
_From @RafaelKr on July 1, 2017 21:12_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**
[x] bug report
[x] feature request (if intentional behaviour)
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Icon not changing.

**Expected behavior:**
The icon should be changed if the variable assigned to tabIcon changes.

**Steps to reproduce:**
http://plnkr.co/edit/iHUDXfoJBCqXa7ZI0UzS?p=preview
When clicking on the bulb-icon in the tabbar, the icon should be changed from `ios-bulb-outline` to `ios-bulb`. In the developer tools you can see `ng-reflect-name="ios-bulb"` is changed on the ion-icon, but the class stays the same.

Also the `enabled`-attribute is not dynamically assignable, but I think that should be an own issue?

_Copied from original issue: ionic-team/ionic#12228_

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. This is actually working as [this plunker](http://plnkr.co/edit/a1bz5QtSlJsRzcPf1kOd?p=preview) shows. The actual issue is that the `ios-bulb` icon and the `ios-bulb-outline` icon seem to be the same. Because of this, I am going to move this issue to the ionicons repo.

**Comment by RafaelKr** [comment]
This is extremely strange, because if I change the class of `ion-icon` manually to `ion-ios-bulb` the icon changes.

Also I tested it with `ios-barcode` and `ios-barcode-outline` - same problem.
But when using `ios-arrow-dropright` and `ios-arrow-dropright-circle` it's working fine, so it has nothing to do with the same beginning of the icon-names.

**Comment by fawzywassel** [comment]
same issue with me

**Comment by amandaejohnston** [comment]
Looks like this has been resolved in the time since it was posted. Using the latest version of Ionicons, I tested both `bulb` and `barcode`, and the outline versions display differently as expected. Note that `ion-tabs` now uses an `ion-icon` component directly, rather than having to go through the `tabIcon` prop, so it's safe to test using `ion-icon` by itself. Thanks for the report, and thank you for using Ionic!
