### ISSUE TITLE
Athletics-themed icons

### ISSUE THREAD

**Issue by wbhob** [ionic-team/ionicons#502]
Hi, Ben and Adam and team! I'd like to request a couple icons (since our app is athletics-focused!) Sorry there are so many, and I may even add a couple later but I don't want to be a chore

-[ ] strength training (like a dumbbell)
-[ ] speed/running (a person running, hurdles, track)
-[ ] icons for more sports
-[ ] spreadsheet
-[ ] a square graph icon

**Comment by amandaejohnston** [comment]
Thank you for the requests! To address these in turn:
- Strength training: since added as `barbell`
- Speed/running: Let's use https://github.com/ionic-team/ionicons/issues/904 to track this
- More sports: we have quite a few of these now: `football`, `basketball`, `tennisball`, `baseball`, `bicycle`
- Spreadsheet and square graph: Not entirely sure what you had in mind here, but I think the existing `grid` covers these?

If you had other particular icons in mind, please open new requests with examples. Thank you!
