### ISSUE TITLE
Icons request: sports icons

### ISSUE THREAD

**Issue by MatanYadaev** [ionic-team/ionicons#506]
I have 2 sports apps which needs sports icon like:
Soccer, basketball, tennis, biking, running, baseball, and more...
Here is a great example for sport icons:
http://www.ultimatedesignertoolkit.com/wp-content/uploads/2015/04/featured2.jpg

**Comment by amandaejohnston** [comment]
Thank you for the request! We've since added a good number of these: `football`, `basketball`, `tennisball`, `baseball`, and `bicycle`. We can use https://github.com/ionic-team/ionicons/issues/904 to track running, and there's also https://github.com/ionic-team/ionicons/issues/602 for outdoor sports. If there are any other particular icons you wanted that aren't already covered by existing issues, please open new request(s). Thanks again!
