### ISSUE TITLE
Loading Icons Missing on V3.0 and V4.0

### ISSUE THREAD

**Issue by vishnutsivan** [ionic-team/ionicons#516]
Loading icons are also missing which is included on V2.0.

![image](https://user-images.githubusercontent.com/18438320/33646898-1f2b5c7c-da78-11e7-85fa-273bf8fb1ad1.png)

**Comment by amandaejohnston** [comment]
Thank you for the request. Possible loading icons include `hourglass`, `time`, `reload`, `reload-circle`, `refresh`, and `refresh-circle`. Ionic Framework also has the `ion-spinner` component, which can render animated loading spinners: https://ionicframework.com/docs/api/spinner

Since Ionicons currently don't include animated icons, I'm going to close this out, but let me know if the above options don't fulfill your use case and I can take another look.
