### ISSUE TITLE
Couldnot use in a Photoshop through Cheatsheet in Ver. 4.1.1 ?

### ISSUE THREAD

**Issue by boozeahead** [ionic-team/ionicons#543]

**Comment by Uranbold** [comment]
We need old Cheatsheet like v2. It has the ability to copy the IconFont character itself. The new version has the problem with it.

Thanks.

**Comment by davydewinne** [comment]
Indeed the cheatsheet was so easy to copy & paste icons to a textfield. Perfect for fast prototyping...
please bring back this possibility!

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. With Ionicons v4 we moved to using SVGs instead of icon fonts. For information on why we moved away from icon fonts please see our [blog post](https://ionic.io/blog/announcing-ionicons-v4) regarding this topic. The Ionicons website has a [cheatsheet](https://ionic.io/ionicons) that lets you download SVGs to be used in other applications.
