### ISSUE TITLE
Security?

### ISSUE THREAD

**Issue by bfischer1121** [ionic-team/ionicons#569]
Hi, first off love these icons - I've used them in every project for many years. Just curious what kind of security measures are in place to prevent the CDN process from being hacked, since ionicons v4 is being hotlinked on thousands of sites/apps now and would be a high value target. Any plans for a self-hosted version of the modern system?

**Comment by Aljodomo** [comment]
+1

**Comment by RupertEverton** [comment]
Hello @bfischer1121 and @Aljodomo , sorry for the ping.
Have you found a solution for self-hosting? I'd be very interested.
Thank you!

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. Ionicons is currently published to NPM: https://www.npmjs.com/package/ionicons. All team members who have publish access for Ionicons must have Two Factor Authentication (2FA) enabled. We also have other security measures in place such as restricting who has publish access. While no security measure is perfect, we think these are important steps to help reduce security risk.

We strongly recommend having Ionicons as a dependency of your project instead of loading it from CDN.

Let me know if you have any additional questions!
