### ISSUE TITLE
Ionicons stop working when using async

### ISSUE THREAD

**Issue by alexnb98** [ionic-team/ionicons#608]
Developing our Marketing Software, we started using ionicons because they are really useful and easy to use. 

But when we load the ionicons script the icons stop displaying. I searched for this error, but I could not find any related issue. 

Do you have any idea why this happens?

**Comment by mattbushell** [comment]
Hi, i was checking if somebody had posted this bug. Ionicons uses some way to inject more javascript source urls, whatever method they are using makes the main ionicons script rely on the need for the additional source injection to be the "last" script while running its own script. If another script gets onto the list then the loading of the icons fails because the new source is pulled relatively from the hosting site's host. It must be using something like elementsByTagName("script")[elementsByTagName.length] to find its rel url. If you are the site owner you can work around this problem by making sure that ionicons is the absolute last lib to be loaded. However this is not useful if your page includes other libs that also inject as the 'other' injections will be inserted.

**Comment by laurentpayot** [comment]
Spot on @mattbushell
To prevent icons from disappearing after some other scripts are loaded I had to dynamically insert the ionicons script in the DOM after an `oncreate` hook of my Svelte app. It just does not feel right :confused:

**Comment by mattbushell** [comment]
In the end i used the Font version of ionicons rather than the fancy and desirable javascript lib. I just couldnt get it to work reliably when developing widgets to be hosted on 3rd party sites that are unfathomable. A fix for this bug, and it is a bug, is to change the way Ionicons secondary script url is derived, or do away with that particular pattern all together. An easyish but hacky fix would be to scan the DOM script array for the ionicons.js string in the urls rather than using "the last scripts host".

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. I am going to close as there is not enough information for us to verify this bug. If this is still a problem with the latest version of Ionicons, please reply to this thread with a GitHub repo that we can use to verify the reported behavior.
