### ISSUE TITLE
box-sizing issue in 4.5.5

### ISSUE THREAD

**Issue by gravsten** [ionic-team/ionicons#662]
When moving to 4.5.5 (from 4.1.2), the box-sizing of `<ion-icon>` has changed to `content-box` (from `border-box`).
And (presumably because it is dynamically loaded by JS) I can't change this back through CSS : computed style is always `content-box`
If 4.5.5 is supposed to be 100% compatible with previous 4.x.x versions, this is a serious bug.
Placement of all icons is altered, which is noticable enough in a nav menu for example.

**Comment by amandaejohnston** [comment]
Thank you for the issue! I don't have context on why this change was made, but since we've released a few major versions in the time since this was posted, I'm going to go ahead and close this out as "won't do."

In the current version, the `box-sizing` is set with an `!important` ([link](https://github.com/ionic-team/ionicons/blob/45c04dda6c905e535083b171cead374b1c993afa/src/components/icon/icon.css#L11)) so it can be overwritten by adding a custom class to the `ion-icon` for higher specificity in your selector, and then using an `!important` of your own.
