### ISSUE TITLE
ionic 4 - icon font instead of svg in web components

### ISSUE THREAD

**Issue by pravesh364** [ionic-team/ionicons#676]
Ionic 4 components are using lazy loading svg file in the web components.

Is there any option to use "icon font" in web components instead of svg/ion-icon?

**Comment by liamdebeasi** [comment]
Hey there,

With Ionicons 5 we moved to using SVGs instead of icon fonts. This reason for this is the icon font required developers to bundle several megabytes of font data with every app, even if they were not using all the icons. With SVGs, developers can include only the icons they need to use in their app. At the moment, we do not have plans to re-introduce the icon font. Thanks for understanding!
