### ISSUE TITLE
Directives for SVG icons

### ISSUE THREAD

**Issue by danieldanielecki** [ionic-team/ionicons#684]
It would be nice to have easily imported Ionicons available [here ](https://ionicons.com/) in form of directives like [Angular](https://github.com/FortAwesome/angular-fontawesome), [React](https://github.com/FortAwesome/react-fontawesome), or [Vue.js](https://github.com/FortAwesome/vue-fontawesome) by Font Awesome 5 has.

In essence, something like `<ion-icon [icon]="add"></ion-icon>` could render a SVG icon. Alternatively `<ion-icon-svg name="add"></ion-icon-svg>` might be also a good addition. Currently to use SVG icons we have to download it, and import from our project assets. Adding similar support for SVG like we have for web fonts (`<ion-icon name="add"></ion-icon>`) could be great.

**Comment by amandaejohnston** [comment]
Thank you for the request! This is possible in the versions released in the time since this was posted. See the usage page for more information: https://ionic.io/ionicons/usage

Due to the age of this issue, I'm going to go ahead and close it. If there's still some missing functionality in the latest version of Ionicons, please open a new issue.
