### ISSUE TITLE
ie11 support

### ISSUE THREAD

**Issue by rexdesigndk** [ionic-team/ionicons#708]
So i've seen it being discussed on here. But no one has really answered. Ionicons is suppose to support ie11 but i haven't been able to get it to work on ie11. 

I get this error when i'm using ionicons 
`Unhandled promise rejection TypeError: Unable to get property 'replace' of undefined or null reference`

**Comment by mariusa** [comment]
From Wikipedia: https://en.wikipedia.org/wiki/Internet_Explorer#Internet_Explorer_11

End of life
Microsoft Edge, officially unveiled on January 21, 2015, has replaced Internet Explorer as the default browser on Windows 10. Internet Explorer is still installed in Windows 10 in order to maintain compatibility with older websites and intranet sites that require ActiveX and other Microsoft legacy web technologies.

Sorry, I recommend not wasting time on IE11.

**Comment by rexdesigndk** [comment]
Believe me i do not like working on IE11. But my current projects requires it :( I've moved over to fontawesome instead
