### ISSUE TITLE
md prefix missing for icons

### ISSUE THREAD

**Issue by jhgeluk** [ionic-team/ionicons#773]
I'm trying to use the following icon in my ionic app: **person-outline**.

However, ionic looks for a file: md-person-outline.svg, this file does not exist in: 
`node_modules/ionicons/dist/ionicons/svg`
And
`www/svg`

But the file person-outline.svg **without the md- prefix does exist**.

Do I need to add the md- prefix manually, what could I do to fix this?

**Comment by rosunad** [comment]
Same problem since I've updated to v5

**Comment by Friedrich-Mocker** [comment]
I use `ios="document`" and `md="document"` instead of `name="document"` now

**Comment by SaltyPotato** [comment]
> I use `ios="document`" and `md="document"` instead of `name="document"` now

Doesn't really seem like a valid solution, since you'll need every icon in your app.

**Comment by dinitri-ragoo** [comment]
Same problem here, just updated to v5  and name of icon with prefix ``ios-``   or   ``md-``  no more working.

_Failed to load resource: the server responded with a status of 404 (Not Found)_

But icons without prefixes are working perfectly.

**Comment by arnotixe** [comment]
just wanted to mention how I got this error: 
1. updated from ionic4 to 5 on android machine, `updated icon names since they vary between v4 and v5`, built & run ok.
2. pushed repo
3. pulled repo on ios and `FORGOT to run npm install` 
4. ran ios -> messages in Xcode on "ios-xxx.svg not found"
5. googled and found this thread

You probably guess what the fix was ? (Hint: `npm install` on ios)

Who knows, maybe it happened to someone else reading this thread in the future :blush:

**Comment by brandyscarney** [comment]
Thanks for the issue! I am not able to reproduce this using latest: https://stackblitz.com/edit/6x53ug?file=index.html

If you are still running into this please provide a code reproduction, thank you!
