### ISSUE TITLE
why ionicons 5 no longer auto switch platform specific icons?

### ISSUE THREAD

**Issue by beenotung** [ionic-team/ionicons#928]
From the release note it seems ionicon will no longer auto choose the icon according to the user device. The developer would have to explicitly specific the icon with ios and md attribute if they prefer the app icons to looks nature to the users.

However, developer without much experience on the other platform may overlook. For example, the traditional share icon on android and iOS looks completely different but they're now organized into separate icon named share and share-social.

https://github.com/ionic-team/ionicons/releases/tag/5.0.0

**Comment by beenotung** [comment]
Also, it seems we cannot specific the md and ios variant of icon in the actionsheet ?

**Comment by bensperry** [comment]
This was a change we made with Ionicons v5, which means you will need to manage icons per platform: 

> At the end of the day, we’d rather not make assumptions about what icons you want on iOS or Android — we’d rather give you full control over which icons you explicitly set for each platform.

We wrote more about why we made the change in this [blog post](https://ionicframework.com/blog/announcing-ionicons-5/). Thanks!

**Comment by beenotung** [comment]
Thanks for more context from the blog. It mentioned ionic still auto choose platform specific icon for back and menu icons, however it seems sharing icon is out of the special list.

Is there an option for developer to opt-in the automatic switching icon functionality ?

**Comment by brandyscarney** [comment]
Thanks for the issue! As Ben shared, the decision was made in order to not assume what developers wanted. We do still handle some platform specific icons in the framework to enhance the native experience. We do not have an option to opt-in as the code to switch between the platforms does not exist, however, you can still achieve this by checking the `mode`, for example passing icon to action sheet:

```typescript
icon: mode === 'md' ? 'heart' : null,
```

You can get the mode in a JavaScript app using 

```typescript
const mode = Ionic.mode;
```

and in Angular using:

```typescript
import { Config } from '@ionic/angular';

constructor(
  public config: Config
) { }
  
ngOnInit() {
  this.mode = this.config.get('mode');
}
```
