### ISSUE TITLE
CDN doesn't work

### ISSUE THREAD

**Issue by kwiat1990** [ionic-team/ionicons#971]
Hi, I'm using Ionic Iocons via CDN for a few months now and in the last couple of days I noticed that the official CDN link (which is also pointed in the ionic documentation) doesn't work anymore: `https://unpkg.com/ionicons@5.5.1/dist/ionicons.js` gives me `Cannot find "/dist/ionicons.js" in ionicons@5.5.1` and on my page I can see `GET https://unpkg.com/ionicons@5.5.1/dist/ionicons.js net::ERR_ABORTED 404`.

The v5.4.0 does work.

**Comment by lugark** [comment]
It seems the last version available on unpkg is 5.4.0

**Comment by bastecklein** [comment]
Same issue.  Seems like this would be an easy fix guys...

**Comment by liamdebeasi** [comment]
Hi everyone,

This has been resolved via https://github.com/ionic-team/ionicons/pull/982, and with Ionicons v5.5.2 the `ionicons.js` file should be working again.

Stencil 1 had a deprecated loader that, when used, automatically added `module` and `nomodule` script tags to your web page. In Stencil 2 that loader was removed in favor of adding the `module` and `nomodule` script tags manually.

Ionicons v5.5 updated its internals to Stencil 2 to better support the custom elements bundle functionality, but in doing so we lost the deprecated loader.

I re-added the deprecated loader so that there is no breaking change in Ionicons v5 functionality, but this loader will be removed in Ionicons v6.

I have updated the usage on the Ionicons website to show the new installation code that we recommend: https://ionic.io/ionicons/usage The installation code that was previously recommended will be supported for all of Ionicons v5.
