### ISSUE TITLE
ion-alert-circled will not display on Android 4.2.2 (Samsung Galaxy Tab 3 - 10inch)

### ISSUE THREAD

**Issue by keithdmoore** [ionic-team/ionicons#99]
This is really strange.  For some reason, the ion-alert-circled icon will not render on my Android 4.2.2 (Samsung Galaxy Tab 3 - 10inch) device.  It will render on my Android 4.4.2 Nexus 7 tablet.  Very strange!  Other icons work fine on both, like the ion-checkmark-circled for example.

**Comment by z1ad** [comment]
Just wanted to add some more information incase someone else comes across this problem as I have. I could not find a solution and have had to workaround by using ion-android-warning instead of ion-alert-circled

I think this is due to a bug in Android 4.2 with rendering of certain character codes. ion-alert-circled is at 0xf100 which doesnt seem to work in this case. it doesnt matter if you use the ttf or woff webfont.

see: https://code.google.com/p/android/issues/detail?id=42322
and: https://code.google.com/p/android/issues/detail?id=26347

**Comment by liamdebeasi** [comment]
Hi everyone,

Thanks for the report and apologies for the delay. I am going to close this as the issue appears to be resolved in newer versions of Ionicons (the version that uses SVG instead of icon fonts). Please follow up on this thread if you are still running into issues.
